FROM benediktkr/poetry:latest
MAINTAINER Benedikt Kristinsson <benedikt@lokun.is>
RUN mkdir /builddir

COPY pyproject.toml /builddir/pyproject.toml
COPY poetry.lock /builddir/poetry.lock
COPY sudoisbot/ /builddir/sudoisbot/


WORKDIR /builddir

ENTRYPOINT ["poetry"]
CMD ["build", "-f", "sdist"]
