FROM benediktkr/poetry:latest
MAINTAINER Benedikt Kristinsson <benedikt@lokun.is>
RUN mkdir /builddir

COPY sudoisbot/ /builddir/sudoisbot/
COPY pyproject.toml /builddir/pyproject.toml
COPY poetry.lock /builddir/poetry.lock

WORKDIR /builddir

ENTRYPOINT ["poetry"]
CMD ["build", "-f", "sdist"]
